apiVersion: apps/v1
kind: Deployment
metadata:
  name: csc547-hpa-node
spec:
  selector:
    matchLabels:
      app: csc547-hpa-node
  replicas: 1
  template:
    metadata:
      labels:
        app: csc547-hpa-node
    spec:
      containers:
        - name: csc547-hpa-node
          image: csc547-hpa-node:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: "0.5"
            requests:
              cpu: "0.25"
