apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: csc547-hpa
spec:
  maxReplicas: 4
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: csc547-hpa-node
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 5
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 0