apiVersion: v1
kind: Service
metadata:
  name: csc547-hpa-node-lb
  labels:
    app: csc547-hpa-node-lb
spec:
  selector:
    app: csc547-hpa-node-lb
  ports:
    - port: 3000
      protocol: TCP
      nodePort: 30001
  type: LoadBalancer
