apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: csc547-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fibonacci-deploy
  minReplicas: 1
  maxReplicas: 25
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 20
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 0
      policies:
        - type: Pods
          value: 2
          periodSeconds: 10
        - type: Percent
          value: 50
          periodSeconds: 10
